### ISSUE TITLE
name vs id

### ISSUE THREAD

**Issue by seblemaguer** [rollacaster/elcontext#2]
Hello,

is there a specific reason that the name is decorellated from the id (assuming that the id is generated by the function (uuid-gen-4))?

**Comment by rollacaster** [comment]
Hi,
it's quite a while since I wrote that code 🙂 But I think I wanted to decouple technical names from user generated names. I did not check the code but by using the ID it should be possible to create contexts with the same name and I do not need to check same name collisions after creation/edit.

**Comment by seblemaguer** [comment]
Hello,

Thanks a lot. Yes I actually put this package on hold for a while but I managed to take the time to play with it. As I tend to do every configuration in elisp, I don't use the "GUI" to create the context. I will update the documentation (I mean I will do a pull request).
